---
config:
  layout: elk
---
classDiagram
    direction LR

%% ========== Services ==========
    class AdminService {
        + managePosts() void
        + manageUsers() void
        - DataStore store
    }
    class AuthService {
        + getCurrentUser() User
        - isRRNUnique(String) boolean
        + signup() void
        - calcGenderFromRRN(String) String
        + ensureDefaultAdmin() void
        - readValidRRN() String
        + login(boolean) void
        + logout() void
        - readValidUserId() String
        - readValidNickname() String
        - isNicknameUnique(String) boolean
        - isUserIdUnique(String) boolean
        - calcAgeFromRRN(String) int
        - DataStore store
        - User currentUser
    }
    class NotificationService {
        + showMyNotifications(User) void
        - DataStore store
    }
    class PostService {
        + manageMyPosts(User) void
        + searchAndView(User) void
        + createPost(User) void
        + getUserRank(User) String
        - DataStore store
    }
    class TradeService {
        + requestTrade(User, Post) void
        + manageTrades(User) void
        - DataStore store
    }
